### ISSUE TITLE
Application running in Tray

### ISSUE THREAD

**Issue by phnz** [VPNht/desktop-legacy#13]
- [x] icon in notification area is pixellated, not really beautiful to the eye
- [x] icon when not connect is almost invisble on win10 if selected color for bar is black
- [x] "Quit and disconnect" makes no sense to me: it's disconnect, then quit.
- [x] "Toogle VPN.ht" means nothing to most people I believe, maybe simply "Show window" or something would be better.

**Comment by luigiplr** [comment]
Fixed in 63819722e64493e94b31dd9b9d0f144c6576f07e
