### ISSUE TITLE
Unable to build release

### ISSUE THREAD

**Issue by zpl** [VPNht/desktop-legacy#27]
Hello, I'm trying to buid release on windows 10, and folowing instructions on main page:

_npm build release_

but there is some git repo not exists:
git clone git@github.com:VPNht/desktop-builder.git util

I think CI fails because of that. is there way to fix it? thanks.

**Comment by wallydz** [comment]
Hello,
I just made the builder public , Enjoy !

**Comment by zpl** [comment]
Thanks!
